"""Initial schema

Revision ID: 94ac1245c1b5
Revises: 
Create Date: 2026-07-28 02:59:19.110416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ac1245c1b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('esp32_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('conveyor_speed', sa.Float(), nullable=True),
    sa.Column('frame_rate', sa.Float(), nullable=True),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esp32_logs_created_at'), 'esp32_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_esp32_logs_device_id'), 'esp32_logs', ['device_id'], unique=False)
    op.create_table('system_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_status_key_name'), 'system_status', ['key_name'], unique=True)
    op.create_table('detections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('defect_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('detection_status', sa.String(length=50), nullable=False),
    sa.Column('esp32_action', sa.String(length=50), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_batch_number'), 'detections', ['batch_number'], unique=False)
    op.create_index(op.f('ix_detections_created_at'), 'detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_detections_defect_type'), 'detections', ['defect_type'], unique=False)
    op.create_index(op.f('ix_detections_detection_status'), 'detections', ['detection_status'], unique=False)
    op.create_index(op.f('ix_detections_device_id'), 'detections', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_device_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detection_status'), table_name='detections')
    op.drop_index(op.f('ix_detections_defect_type'), table_name='detections')
    op.drop_index(op.f('ix_detections_created_at'), table_name='detections')
    op.drop_index(op.f('ix_detections_batch_number'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_system_status_key_name'), table_name='system_status')
    op.drop_table('system_status')
    op.drop_index(op.f('ix_esp32_logs_device_id'), table_name='esp32_logs')
    op.drop_index(op.f('ix_esp32_logs_created_at'), table_name='esp32_logs')
    op.drop_table('esp32_logs')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
